FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _beach_shertigan_data
_beach_shertigan_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,256,256

@instruments:
	.byte $b0 ;instrument 00 (Comp)
	.word @env1, @env0, @env0
	.byte $00
	.byte $70 ;instrument 01 (Melo)
	.word @env1, @env5, @env0
	.byte $00
	.byte $30 ;instrument 02 (Mer)
	.word @env8, @env2, @env0
	.byte $00
	.byte $30 ;instrument 03 (Vague Attack)
	.word @env11, @env0, @env0
	.byte $00
	.byte $30 ;instrument 04 (Vague Decay 1)
	.word @env10, @env0, @env0
	.byte $00
	.byte $30 ;instrument 05 (Vague Decay 2)
	.word @env9, @env0, @env0
	.byte $00
	.byte $30 ;instrument 06 (Vague Decay 3)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 07 (Vague Decay 4)
	.word @env6, @env0, @env0
	.byte $00
	.byte $30 ;instrument 08 (Vague Decay 5)
	.word @env4, @env0, @env0
	.byte $00
	.byte $30 ;instrument 09 (Vague Decay 6)
	.word @env3, @env0, @env0
	.byte $00
	.byte $30 ;instrument 0a (Vague Decay 7)
	.word @env7, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $c0,$3b,$be,$00,$02
@env3:
	.byte $c6,$7f,$00,$00
@env4:
	.byte $c5,$7f,$00,$00
@env5:
	.byte $bf,$c0,$00,$01
@env6:
	.byte $c4,$7f,$00,$00
@env7:
	.byte $c7,$7f,$00,$00
@env8:
	.byte $c1,$0d,$c2,$04,$c3,$03,$c4,$02,$c5,$02,$c6,$05,$c7,$c7,$c6,$05,$c5,$04,$c4,$03,$c3,$07,$c2,$0d,$c1,$00,$18
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $c1,$7f,$00,$00
@env11:
	.byte $c1,$02,$c2,$02,$c3,$02,$c4,$02,$c5,$02,$c6,$02,$c7,$02,$c8,$02,$c9,$00,$10
@song0ch0:
	.byte $fb, $08
@song0ch0loop:
	.byte $82
@song0ref5:
	.byte $5e, $89, $00, $85, $56, $00, $50, $00, $56, $89, $00, $85, $50, $00, $56, $00, $5a, $00, $64, $00, $5e, $89, $00, $85
	.byte $5a, $00, $56, $00, $5a, $87, $00, $56, $83, $00, $50, $00, $56, $00, $5a, $00, $5c, $00
	.byte $ff, $0c
	.word @song0ref5
	.byte $4c, $00, $50, $00, $56, $00, $68, $00, $64, $89, $00, $85, $5f, $01, $64, $87, $00, $5e, $83, $00, $5a, $83, $00, $56
	.byte $83, $00, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref81:
	.byte $27, $01, $2e, $00, $26, $00, $26, $00, $2e, $00, $87, $21, $01, $26, $00, $20, $00, $20, $00, $26, $00, $20, $00, $26
	.byte $00, $2f, $01, $34, $00, $2e, $00, $2e, $00, $34, $00, $87, $35, $01, $3c, $00, $34, $00, $34, $00, $3c, $00, $34, $00
	.byte $3c, $00
	.byte $ff, $32
	.word @song0ref81
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $f9, $85, $f9, $85, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref146:
	.byte $84, $4e, $bd, $86, $50, $8d, $94, $51, $92, $51, $90, $51, $8e, $51, $8c, $50, $85, $8a, $50, $85, $88, $50, $8d
	.byte $ff, $0e
	.word @song0ref146
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $f9, $85, $f9, $85, $fd
	.word @song0ch4loop
