
FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _beach_shertigan_data
_beach_shertigan_data:
	.word @ft_song_list
	.word @ft_instrument_list
	.word @ft_sample_list
	.word @ft_samples
	.byte 0 ; flags
	.word 3600 ; NTSC speed
	.word 3000 ; PAL speed
; FamiTracker exported music data: Mer2.ftm
;

; Module header
	;.word ft_song_list
	;.word ft_instrument_list
	;.word ft_sample_list
	;.word ft_samples
	;.byte 0 ; flags
	;.word 3600 ; NTSC speed
	;.word 3000 ; PAL speed

; Instrument pointer list
@ft_instrument_list:
	.word @ft_inst_0
	.word @ft_inst_1
	.word @ft_inst_2
	.word @ft_inst_3
	.word @ft_inst_4
	.word @ft_inst_5
	.word @ft_inst_6
	.word @ft_inst_7
	.word @ft_inst_8

; Instruments
@ft_inst_0:
	.byte 3
	.word @ft_seq_2a03_0
	.word @ft_seq_2a03_1

@ft_inst_1:
	.byte 1
	.word @ft_seq_2a03_5

@ft_inst_2:
	.byte 1
	.word @ft_seq_2a03_10

@ft_inst_3:
	.byte 1
	.word @ft_seq_2a03_15

@ft_inst_4:
	.byte 1
	.word @ft_seq_2a03_20

@ft_inst_5:
	.byte 1
	.word @ft_seq_2a03_25

@ft_inst_6:
	.byte 1
	.word @ft_seq_2a03_30

@ft_inst_7:
	.byte 1
	.word @ft_seq_2a03_35

@ft_inst_8:
	.byte 1
	.word @ft_seq_2a03_40

; Sequences
@ft_seq_2a03_0:
	.byte $4B, $FF, $00, $00, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $02, $02
	.byte $02, $02, $02, $03, $03, $03, $03, $04, $04, $04, $05, $05, $05, $06, $06, $06, $06, $06, $06, $07
	.byte $07, $06, $06, $06, $06, $06, $06, $05, $05, $05, $05, $05, $04, $04, $04, $04, $03, $03, $03, $03
	.byte $03, $03, $03, $03, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $01
@ft_seq_2a03_1:
	.byte $4B, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	.byte $00, $00, $00, $00, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE
@ft_seq_2a03_5:
	.byte $19, $FF, $00, $00, $01, $01, $01, $02, $02, $02, $03, $03, $03, $04, $04, $04, $05, $05, $05, $06
	.byte $06, $06, $07, $07, $07, $08, $08, $08, $09
@ft_seq_2a03_10:
	.byte $01, $FF, $00, $00, $07
@ft_seq_2a03_15:
	.byte $01, $FF, $00, $00, $06
@ft_seq_2a03_20:
	.byte $01, $FF, $00, $00, $05
@ft_seq_2a03_25:
	.byte $01, $FF, $00, $00, $04
@ft_seq_2a03_30:
	.byte $01, $FF, $00, $00, $03
@ft_seq_2a03_35:
	.byte $01, $FF, $00, $00, $02
@ft_seq_2a03_40:
	.byte $01, $FF, $00, $00, $01

; DPCM instrument list (pitch, sample index)
@ft_sample_list:

; DPCM samples list (location, size, bank)
@ft_samples:


; Song pointer list
@ft_song_list:
	.word @ft_song_0

; Song info
@ft_song_0:
	.word @ft_s0_frames
	.byte 1	; frame count
	.byte 64	; pattern length
	.byte 8	; speed
	.byte 150	; tempo
	.byte 0	; initial bank


;
; Pattern and frame data for all songs below
;

; Bank 0
@ft_s0_frames:
	.word @ft_s0f0
@ft_s0f0:
	.word @ft_s0p0c0, @ft_s0p0c0, @ft_s0p0c0, @ft_s0p0c3, @ft_s0p0c0
; Bank 0
@ft_s0p0c0:
	.byte $00, $3F

; Bank 0
@ft_s0p0c3:
	.byte $E0, $18, $1F, $E1, $19, $07, $82, $01, $E2, $19, $E3, $19, $E4, $19, $E5, $19, $84, $E6, $19, $03
	.byte $E7, $19, $03, $E8, $19, $07


; DPCM samples (located at DPCM segment)
