//-----Visual Novel content!! °˖✧◝(⁰▿⁰)◜✧˖°
//0'v' 1 :) 	2 :| 3 :( 4 :D 5 D: 6 A_A 7 / 8 \ 9 é 10 è
const Passage SCRPT[] = {
{N, "At the end of the afternoon, you're walking on the beach."},
{N, "There are few people here. It's quiet."},
{N, "Rhythm by the sound of the sea, you advance on the sand."},
{N, "You finally find the person you were looking for"},
//Show ANGE
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{H, "show"},
{A, "Ah, there you are!"},
{SWPM, "1"},
{A, "It's good to see you, how are you?"},
{C, "0"},

//> "Yes, I'm fine! And you?"},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "I'm doing well too, very well indeed!"},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "I was a bit afraid we wouldn't get together,"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "but in the end there was nothing to worry about!"},
{J, "47"},

//> "Sorry for the delay"
{SWPM, "4"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Don't apologize, you're here, that's the main thing!"},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "And I was able to enjoy the scenery while I was waiting!"},
{J, "47"},

//> "It was hard to find you."
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Haha, were my directions that vague?"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Sorry, I don't know much about the region."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But I didn't think this beach was too bad"},
{SWPM, "1"},
{A, "At least it's quiet here!"},

{SWPEL, "6"},
{SWPER, "6"},
{N, "His attention is then turned to the sea."},
{N, "She is calm, steady, and stretches as far as the eye can see"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It's beautiful, don't you think?"},
{C, "1"},

//> "Yes, it's very nice!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I can see that you enjoy the view as much as I do"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "If I could, I would stay here all my life"},
{SWPEL, "3"},
{SWPER, "3"},
{SWPM, "4"},
{A, "Well, it wouldn't be very comfortable in the long run," },
{J, "77"},

//> "Bof, c'est la mer quoi."},
{SWPEL, "3"},
{SWPER, "6"},
{SWPM, "4"},
{A, "Hehe, you still don't have an artist's soul."},
{SWPEL, "0"},
{SWPER, "0"},
{A, "And that's okay, you have the right to find it trivial"},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "After all, it's a bit absurd to dwell on it here"},

{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "But for a date it's still a very good place."},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Now my connection is no longer a problem."},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "And it's much nicer than in video!"},

{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Well, now that you're here I wanted to ask you..."},
{SWPM, "4"},
{A, "Remember your project? The one you told me about?"},
{SWPM, "1"},
{A, "He looked interesting, how's it going?"},
{C, "2"},

//> I can see the end of it!
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Great! There's something to be proud of!"},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "You know, I really admire your determination"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "You often say I'm exaggerating, but I mean it!"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Just talking to you motivates me a lot!"},
{J, "178"},

//> I'm having trouble moving forward...
{SWPM, "3"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Oh boy, excuse me... I hope it's all right!"},
{SWPM, "1"},
{A, "Don't make yourself sick about it,"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It's normal to have periods of doubt."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Maybe you just need to rest!"},
{SWPM, "1"},
{A, "Have you thought about asking for help?"},
{C, "3"},
//>Yes
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},	
{A, "Great, I think you're on the right track!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Remember to talk about your doubts with these people,"},
{SWPM, "1"},
{A, "Sometimes just talking helps to find a solution"},
{SWPEL, "3"},
{SWPER, "3"},
{SWPM, "1"},
{A, "At least that's what happens to me when we talk!"},
{J, "178"},

//>I don't know if it would help me
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "0"},
{A, "You know, there's no shame in asking for help."},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "But I understand, it's not always easy"},
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I'll... I'll help you if you want!"},
{SWPM, "1"},
{A, "But you probably have better friends than me!"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "In any case don't stay alone, promise?"},
{J, "178"},

//> I've moved on
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Oh okay, excuse me!"},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It's okay, you have the right to change." },
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "If we put all our ideas into practice we wouldn't get away with it."},
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A,"(although I shouldn't do the complete opposite)"},

{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "By the way... I don't know if you remember..."},
{SWPM, "4"},
{A, "But recently you encouraged me to send in my CV"},
{SWPM, "2"},
{A, "I didn't think I'd get any results to be honest"},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "But someone answered!"},
{C, "4"},

//>Too good!
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Haha, thank you very much! But all is not won."},
{SWPM, "2"},
{A, "They invited me for an interview, but..."},
{J, "204"},

//> What did they tell you?
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Well..."},
{SWPM, "4"},
{A, "I think I have a job interview..."},

{SWPM, "3"},
{A, "But it scares me a little"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "You see, I haven't been working for a long time"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I've even forgotten how these interviews are conducted"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Do you know what you're into?"},
{C, "5"},

//>It's just questions
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Oh okay, they just want to get to know me?"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It's kind of like a love date, hehe"},
{SWPM, "5"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But you have to dress for a date, don't you?"},
{SWPM, "2"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Arg, I have no idea what I'm going to wear!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "A shirt maybe? Or a suit is better?"},
{J, "281"},

//> They're not gonna eat you haha
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Haha, you're right. I'm overthinking things."},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But it's still an important moment,"},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "I wouldn't want to do anything haha"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "For example, I have read articles on the subject,"},
{SWPEL, "9"},
{SWPER, "10"},
{SWPM, "2"},
{A, "And they advise to dress well, but I hesitate."},
{SWPEL, "9"},
{SWPER, "10"},
{SWPM, "4"},
{A, "Do I really have to wear a shirt? What do you think?"},
{J, "281"},

//>I forgot me too
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Haha, I'm not the only person in this case"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It makes me feel a little better, I confess."},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "In the end it shouldn't be that complicated."},
{SWPM, "3"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But I'm afraid of doing something wrong"},
{SWPM, "2"},
{A, "Like, should I put on a... shirt?"},
{C, "6"},

//>Yes, it looks serious.
{SWPM, "1"},
{SWPEL, "10"},
{SWPER, "9"},
{A, "All right, all right, I have to look professional!"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "If I make a good impression they'll trust me"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Yes, it makes sense!"},
{SWPM, "3"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "...now I'm going to have to find a shirt."},
{SWPM, "2"},
{A, "Maybe I have one in my closet..."},
{SWPM, "1"},
{A, "It dates, I only use it for weddings."},
{SWPEL, "7"},
{SWPER, "8"},
{A, "(and I'm not often invited)"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But that should do it!"},
{J, "357"},

//> No, be casual'.
{SWPM, "4"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Phew, I was afraid I'd have to dress like a penguin!"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "So, a more relaxed outfit..."},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "Um, I could take out my teenage shirt."},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "But you probably didn't mean that haha"},
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A, "What will they think of me if I come up with that?"},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I think I need to do some testing before I make up my mind"},
{J, "357"},

//>Wear what you like
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Oh, that's nice!" },
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Maybe you're right, I have to trust myself"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But you know, I don't pay much attention to what I'm wearing"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Even here I'm wearing my grey sweater, like every day."},
{SWPM, "2"},
{A, "I've never really thought about what I like"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "I'll have to experiment with what I have!"},

{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Say, can I send you pictures of my essays?"},
{C, "7"},

//> Of course!
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Thank you! I knew I could count on you!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Just an outside opinion will help me a lot to choose."},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It's better than relying on my fashion sense."},
{J, "394"},

//>I can't help you /////////----////////
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "No, you're exaggerating!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I'm just asking for your honest opinion, that's all!"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "You're someone I trust for that"},
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "And if I want to embarrass myself, it's not in front of a stylist"},
{C, "8"},
//>Good, if you insist
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Thank you very much! I owe you one!"},

{SWPM, "4"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Okay, I'll stop bothering you with my worries." },
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Is there anything in particular you want to do?"},
{C, "20"},
//>How about buying an ice cream?
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Oh yes! Great idea!"},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "They say they sell every perfume imaginable here."},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "What's your favorite perfume?"},
{C, "9"},

//>Vanilla
{SWPM, "4"},
{A, "Oh, I see you're the classic type!"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "That's just like me, I love vanilla."},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "It's such a sweet taste that tickles the taste buds." },
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "I always chose this perfume as a child!"},
{SWPM, "1"},
{A, "And even grown-up for that matter!"},
{J, "643"},

//>Chocolate
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "0"},
{A, "Hehe, chocolate, it suits your style."},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I really like chocolate, but on ice cream it's...weird."},
{SWPM, "8"},
{A, "As if they were using a totally different flavor."},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Don't you think? Or am I making films for myself?"},
{C, "21"},
//>I agree
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Ah! It's nice to know I'm not delirious."},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But in any case you have the right to love!"},
{J, "643"},
//>I think it's movies
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "It's quite possible!"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Maybe I just haven't been tasting the right brands"},
{SWPM, "4"},
{A, "You'll recommend it to me one of these days!"},
{J, "643"},

//>Fruit
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Nice, and it suits the summer mood!"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I really need to eat more fruit,"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But then in ice cream, it reminds me of my grandmother"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "She offered me some at each of my visits."},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Well, that was to be expected after a while."},
{SWPEL, "3"},
{SWPER, "3"},
{A, "But it's still nice memories!"},
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Oops! I'm still talking about myself too much."},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Excuse me, I don't mean to do this"},
{J, "643"},

//>Peu importe
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Oh okay, you're not very ice creamy?"},
{C, "10"},
//>I love all perfumes
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Ah, knowing you, I'm not surprised indeed!"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "We'll see what there is and what you want." },
{J, "643"},
//jump here

 //> Not too much
{SWPM, "2"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "Oh okay..."},
 {SWPM, "4"},
 {SWPEL, "9"},
 {SWPER, "10"},
 {A, "I understand, you were just offering that to please me?"},
{SWPM, "1"},
 {A, "That's nice, but you don't have to force yourself, you know"},
 {SWPEL, "3"},
 {SWPER, "3"},
 {A, "Forget the ice cream, but thanks for offering!"},
 {SWPM, "4"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "Besides, it's really nice on the beach, isn't it?" },
 {SWPM, "1"},
 {SWPEL, "6"},
 {SWPER, "6"},
 {A, "I prefer to stay here, it's quieter"},
 {SWPM, "1"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "By the way, did you see they're having a party in town?"},
 {N, "Indeed, when you arrived you thought you heard music."},
{SWPM, "2"},
 {A, "From what I understand, it's a big annual festival."},
 {SWPM, "1"},
 {SWPEL, "9"},
 {SWPER, "10"},
 {A, "If I can avoid mixing with the crowd, it's better."},
{N, "If you pay attention, you can better locate the sounds of the city"},
 {N, "From here you hear singing and festive noises"},
 {N, "There must be a lot of people out there."},
 {N, "And maybe that's why the beach is deserted."},
 {SWPM, "2"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "Do you have trouble with crowds?"},
{C, "11"},
 //>Yes, I can't stand it
 {SWPM, "1"},
 {SWPEL, "3"},
 {SWPER, "3"},
 {A, "You're kind of like me then."},
 {SWPM, "2"},
 {SWPEL, "9"},
 {SWPER, "10"},
 {A, "Sometimes I get stressed just thinking about it."},
 {SWPEL, "6"},
 	{SWPER, "6"},
 {A, "Getting out of my house is already a challenge,"},
 {SWPM, "3"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "So partying, you can't go in real life"},
{SWPM, "2"},
 {A, "But it's not really the same thing here"},
 {SWPM, "4"},
 {A, "And then you're here, we can support each other!"},
{J, "904"},

 //>It doesn't really bother me.
 {SWPM, "4"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "Don't you have any special problems? That's great!"},
 {SWPM, "2"},
{A, "I mean, I wish I could be like you."},
{SWPM, "1"},
 {SWPEL, "9"},
{SWPER, "10"},
{A, "Don't necessarily like it, but be more neutral."},
{SWPM, "2"},
 {A, "Don't stress just at the thought of seeing people..."},
{SWPM, "3"},
 {SWPEL, "6"},
 	{SWPER, "6"},
 {A, "..."},
 {SWPM, "3"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "Excuse me."},
{SWPM, "1"},
 {SWPEL, "1"},
 {SWPER, "1"},
 {A, "A lot of things are stressing me out anyway,"},
 {SWPM, "1"},
 {SWPEL, "0"},
 {SWPER, "0"},
{A, "I think you're getting to know me!"},
{SWPM, "2"},
 {A, "I'm like this, I don't know if I'll ever change"},
 //{A, "But this reason that I am in your company."}, //Line to delete? Double
 //{A, "You accept me, even when I find it hard to do so.},
 //{A, "And it makes me feel good."},
{J, "904"},

 //>I love the crowd!
{SWPM, "4"},
 {SWPEL, "3"},
 {SWPER, "3"},
 {A, "Really? That's crazy!"},
{SWPM, "1"},
 {A, "It's true that you're going to party a lot"},
 {SWPEL, "9"},
 {SWPER, "10"},
 {A, "Well, more than me, that's for sure!"},
 {SWPM, "4"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "You have a festive spirit, that's probably a good thing." },
 {SWPM, "1"},
 {SWPEL, "1"},
 {SWPER, "1"},
{A, "I'm kind of at odds with that"},
{SWPM, "4"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "But, you know, that's what I like about our friendship"},
{SWPM, "1"},
 {SWPEL, "6"},
 {SWPER, "6"},
 {A, "We're such different people,"},
 {SWPEL, "3"},
 {SWPER, "3"},
 {A, "but we understand each other."},
{SWPM, "4"},
 {SWPEL, "0"},
 {SWPER, "0"},
 {A, "It's very rewarding, don't you think?"},
 {SWPM, "1"},
 {SWPEL, "6"},
 {SWPER, "6"},
 {A, "Then it would be hard to find people like me"},
{SWPM, "2"},
 {A, "Well, I think..."},
{J, "904"},//TODO CHANGE VALUE LATER

//---

{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Uh, but I have to confess..."},
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A, "I don't really have any money on me"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Really, excuse me!"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "You see, I had to buy equipment for my house."},
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "And as a result... it's a bit ric rac at the moment."},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Do you mind walking me?"},
{C, "12"},

//> I was going to offer it to you
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "W... really?"},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Thank you very much! That's so nice of you."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I promise, as soon as I can, I'll return the favor!"},
{J, "714"},

//>Penses to reimburse me
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Yes! You have my word!"},
{SWPM, "1"},
{A, "Good accounts make good friends after all."},
{SWPEL, "0"},
{SWPER, "0"},
{A, "And it's already very nice of you to come forward!"},
{SWPM, "4"},
{A, "I promise, in a couple of days I'll be able to pay you back"},
{J, "714"},

//>Frank, abuse you
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Haha, sorry, I know it's not the first time."},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "But after all you're the one who offered the ice cream!"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Go! I promise, this is the last one."},
{C, "22"},
//> The last one?
{SWPM, "1"},
{SWPEL, "10"},
{SWPER, "9"},
{A, "The last one! Word of the Angel!"},
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A, "(if I stop cracking on trinkets...)"},
{J, "714"},

{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Let's go!"},
{H, "hide"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{N, "You are moving quietly towards the coastal city"},
{N, "Festive music comes to your ears."},
//{N, "You hear the whistling of fusees and confetti."},//

{N, "This is the time of the annual festival,"},
{N, "and the crowd is having a blast." },
{N, "You make sure that Angel is always behind you."},
{H, "show"},
{A, "Don't worry... I'm with you!"},
{H, "hide"},
{N, "You're moving through the city towards the ice booth"},
{N, "Around you are flying confetti and fireworks."},
{N, "Most of the crowd is dancing in the main square."},
{N, "You understand better why the beach was so empty"},
{N, "You finally get to the ice cream store"},
{N, "After inspecting the menu, you turn to Ange."},
{C, "13"},

//>Everything makes me want it!
//> Take what you want
//>It's really expensive!
//> Don't you want a pancake instead?

{N, "But when you turn around, you don't see anyone."},
{N, "Angel is no longer behind you."},
{N, "You get out of the store quickly"},
{N, "Nobody"},
{N, "Misery, Angel must have lost you along the way."},
{N, "With your mind full of anxiety, you begin your research"},
{C, "14"},

//> Ask a passer-by
{N, "You call out to a passer-by, hoping to get some info"},
{N, "\"Someone in a gray sweater? Here it's not common haha\""},
{N, "\"Now everyone wears the summer collection!\"" },
{N, "\"Class, right? Wait till you see my new dance!\""},
{N, "\"He'll outlive your gray sweater, come party!\""},
{N, "That guy was nice, but didn't get you anywhere." },
{N, "People here are too busy partying to help you."},
{C, "14"},

//> Search in the crowd
{N, "If Ange lost you, it's probably because of the crowd." },
{N, "Bravely, you slip in between the dancers looking for him"},
{N, "You can see you're embarrassed, but it's in the name of friendship"},
{N, "In the square, you climb up to the central fountain"},
{N, "Raising you up will help you more in your research"},
{N, "You overlook the crowd with your eyes, but you don't succeed"},
{N, "Yet his gray clothes are easily spotted,"},
{N, "Especially in the maree of colorful costumes."},
{N, "You scan the crowd one last time, just in case."},
{N, "But you finally get around to changing your strategy"},
{C, "14"},

//> Back to the beach
{N, "You turn back to the beach."},
{N, "Maybe Ange is somewhere on the road." },

{N, "You're careful to look all around you"},
{N, "Inspecting alleys and detours in case Ange is there."},
{N, "You go out of town, and still no trace."},
{N, "But back on the beach, you find a familiar face again"},
{H, "show"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Ah, there you are!"},

{C, "15"},
//> No it is you who is here!
{SWPM, "3"},
{A, "Oh no, you were looking for me, weren't you?"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I'm sorry... I didn't mean to worry you."},
{SWPM, "2"},
//{A, "I felt bad in the middle of the crowd.},
{A, "It's just... in the middle of the crowd I wasn't well..."},
{J, "801"},

//> What happened?
{SWPM, "3"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Well...in the middle of the crowd, I wasn't very well."},
{J, "801"},

//>Are you all right?
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Yes, I'm fine, don't worry about me!"},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Anyway, I'm better now!"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It's just... crowds aren't really my thing."},

{SWPM, "2"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "I knew about the festival, but I didn't think so..."},
{SWPEL, "0"},
{SWPER, "0"},
{A, "small. I didn't think I'd see so many people here."},
{SWPEL, "9"},
{SWPER, "10"},
{A, "The noise distracted me, and someone pushed me around"},
{SWPM, "1"},
{A, "It was enough to make me lose sight of you." },
{SWPM, "4"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "But fortunately I'm used to it!"},
{C, "16"},

//> The habit?
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A, "Yes, as a child I had a mania for getting lost in the supermarket"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It happened every time something distracted me"},
{SWPM, "3"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "As soon as I looked away, my mother had disappeared."},
////>That's why you came back?
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
//{A, "That's right, my mother taught me that!" },
{A, "So she taught me what to do if I had a problem:"},
{SWPM, "4"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "Go back to the cash register and wait for Mommy!"},
{SWPM, "1"},
{SWPEL, "7"},
{SWPER, "8"},
{A, "At last here it's a picture hehe! hehe"},
{C, "17"},

//> You've picked up some good habits
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Haha, if you can call it that!"},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "It's true that thanks to this we were able to find each other"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Sorry again, next time I'll be careful!"},
{J, "892"},

//> In the end, we were able to find ourselves
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "Yes, that's the main thing!"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I'm sorry again for making you worry!"},
{J, "892"},

//>You don't talk much about your mother.
{SWPM, "2"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Oh... uh..."},
{SWPM, "1"},
{A, "Do you think so? I don't see why we have to talk about it any more..."},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I think I'm talking a lot about my life already"},
{SWPM, "5"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It bothers you, doesn't it? I'd be more careful!"},
{SWPM, "3"},
{A, "I'm sorry, it was stupid to say that kind of cho-"},
{C, "18"},
//> It's nothing
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Ah... okay..."},
{SWPEL, "7"},
{SWPER, "8"},
{A, "I think my emotions have gotten the better of me again..."},
{SWPM, "4"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Let's talk about something else, if you don't mind"},

{SWPM, "5"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Well, in the end we still don't have our ice cream!"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "It's silly, we've made this expedition for nothing"},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "But that's all right, we'll do it some other time"},

{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{N, "His attention is again drawn to the horizon."},
{N, "The day is now well advanced,"},
{N, "and the sun gradually descends into the sky."},
{N, "Its rays reflect strangely on the blue water."},
{N, "It's really a great show"},
{N, "Suddenly, Angel notices something on the horizon."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Oh look! There's a boat there!"},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "I wonder who it belongs to."},
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It must be nice to have your house on the water."},
{SWPM, "1"},
{A, "I could travel without leaving my house haha"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "One day maybe..."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Do you like to travel?"},
{C, "19"},

//>Yes, all over the world!
{SWPEL, "3"},
{SWPER, "3"},
{A, "Woah, you really have a taste for adventure!"},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "There must be so much to see in the world"},
{SWPM, "4"},
{A, "I like to learn more by watching documentaries,"},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "But I'm sure there is much more to discover"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "I've probably told you this before, but I envy you very much."},
{SWPEL, "0"},
{SWPER, "0"},
{SWPM, "4"},
{A, "It's like you're living more than me..."},
{J, "993"},

//>Yes, but close to my house
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "It's not silly, there are some nice places around your house"},
{SWPM, "2"},
{A, "I wonder what's in my area"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "I've never looked for one, but there must be some."}, //fall flat
{SWPM, "4"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "I think I would do that if I decide to travel"},
{SWPM, "1"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "At least I can go home anytime"},
{J, "993"},

//> No not at all
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Oh, so you're kind of like me"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "It's true that you feel at home in your cocoon."},
{SWPM, "1"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "If I could, I would never go out"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "But I shouldn't have to do this all my life, should I?"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "I'll have to get my act together"},

//main and last branch
{SWPM, "2"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "I hope one day to have a little more courage."},
{SWPM, "1"},
{A, "You know, even a meeting here makes me stressed out"},
{SWPM, "2"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Sometimes I wonder what I'm going to become"},
{SWPM, "3"},
{A, "Sometimes I é¤ £"},
{SWPM, "2"},
{SWPEL, "6"},
{SWPER, "6"},
{A, "..."},
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Excuse me, it's my emotions again"},
{SWPM, "2"},
{A, "You know, I don't know why you're staying with me"},
{SWPM, "4"},
{A, "I'm not a very interesting person."},
{SWPM, "2"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "Just a little thing that tries to get through life"},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "But you're always there to listen, to advise me"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "We certainly have differences, but at least you do..."},
{SWPM, "1"},
{SWPEL, "1"},
{SWPER, "1"},
{A, "..."},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "That's why I enjoy your company so much." },
{SWPM, "1"},
{SWPEL, "9"},
{SWPER, "10"},
{A, "You accept me, even when I find it hard to do so"},
{SWPM, "1"},
{SWPEL, "3"},
{SWPER, "3"},
{A, "And that makes me feel good... "},
{SWPM, "4"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Hey, how would you like to go and pick up some roosters?"},
{SWPM, "3"},
{SWPEL, "0"},
{SWPER, "0"},
{A, "Why are you doing that head?"},
{SWPM, "11"},
{SWPEL, "11"},
{SWPER, "11"},
{A, "....é£;...."},
{H, "hide"},
{N, " "},
{N, "Connexion lost..."},
{N, "Ange is disconnected"}
};

const Choice ListeChoix[]= {
{"Yes, I'm fine! And you?", 12},
{"Sorry for the delay",24},
{"It was hard to find you",33},

{"Yes, it's very pretty!",55},
{"Bof, c'est la mer quoi.",66},

{"I can see the end of it!", 97},
{"I'm having trouble moving forward...",113},
{"Yes",129},
{"I don't know if it would help me", 143 },
{"I've moved on", 162},

{"Too good!",191},
{"What did they tell you?",198},

{"It's just questions",218},
{"They're not going to eat you haha",238},
{"I've forgotten me too",263},

{"Yes, it sounds serious",282},
{"No, be casual' ",310},
{"Wear whatever you like",335},

{"Of course!",362},
{"I can't help you",374},
{"Well, if you insist",390},

{"Vanilla",416},
{"Chocolate",433},
{"Fruit",468},
{"Whatever",499},
{"I love all perfumes",504},
{"Not too much",512},

 {"Yes, I can't stand it",554},
 {"It doesn't really bother me",573},
 {"I love crowds!",604},

//--Ice branch
{"I was going to give it to you",667},
{"Think about paying me back",680},
{"Frankly, you're abusing it",692},

{"Everything makes me envy!", 737},
{"Take what you want",737},
{"It's really expensive!",737},
{"Wouldn't you like a pancake instead?",737},

{"Ask a passer-by",744},
{"Search the crowd",752},
{"Return to the beach",763},

{"No, you're here!",775},
{"What happened?",784},
{"Are you all right?", 789},

{"Habit?",818},
{"And so you waited for me here",1},

{"It's a good reflex",842},
{"In the end we were able to find each other again",855},
{"You don't talk much about your mother",864},
{"It's nothing",881},
//--Main and last branch (?)
{"Yes, all over the world!",935},
{"Yes, but close to home",956},
{"Not at all",974},

{"How about ice cream?",403},

{"Yeah, I agree",448},
{"I think that's just you",457},

{"The last?",705},

};

const char ChoiceCollection[][5] = {
//{nb_choice,choice,...};
{3,0,1,2},
{2,3,4},
{3,5,6,9},
{2,7,8},
{2,10,11},

{3,12,13,14},
{3,15,16,17},

{2,18,19},
{1,20},

{4,21,22,23,24}, //vanilla, chocolate ...
{2,25,26},
{3,27,28,29}, // Ice-less branch
{3,30,31,32},

{4,33,34,35,36},

{3,37,38,39},

{3,40,41,42},

{1,43,43}, //

{3,46,45,47},
{1,48},
{3,49,50,51},//where you want to travel

{1,52}, // what about buying an ice cream?
{2,53,54}, // I agree // I think it's movies...
{1.55}, //The last one?
};